
# constraints

set_property  -dict {PACKAGE_PIN  L3    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_data_clk_p]
set_property  -dict {PACKAGE_PIN  L2    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_data_clk_n]
set_property  -dict {PACKAGE_PIN  W8    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_p[0]]
set_property  -dict {PACKAGE_PIN  Y8    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_n[0]]
set_property  -dict {PACKAGE_PIN  R7    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_p[1]]
set_property  -dict {PACKAGE_PIN  T7    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_n[1]]
set_property  -dict {PACKAGE_PIN  U8    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_p[2]]
set_property  -dict {PACKAGE_PIN  V8    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_n[2]]
set_property  -dict {PACKAGE_PIN  U9    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_p[3]]
set_property  -dict {PACKAGE_PIN  V9    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_n[3]]
set_property  -dict {PACKAGE_PIN  R8    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_p[4]]
set_property  -dict {PACKAGE_PIN  T8    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_n[4]]
set_property  -dict {PACKAGE_PIN  R6    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_p[5]]
set_property  -dict {PACKAGE_PIN  T6    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_data_n[5]]
set_property  -dict {PACKAGE_PIN  K4    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_frame_p]
set_property  -dict {PACKAGE_PIN  K3    IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports phy_rx_frame_n]
set_property  -dict {PACKAGE_PIN  AF7   IOSTANDARD LVDS} [get_ports phy_fb_clk_p]
set_property  -dict {PACKAGE_PIN  AF6   IOSTANDARD LVDS} [get_ports phy_fb_clk_n]
set_property  -dict {PACKAGE_PIN  AB7   IOSTANDARD LVDS} [get_ports phy_tx_data_p[0]]
set_property  -dict {PACKAGE_PIN  AC7   IOSTANDARD LVDS} [get_ports phy_tx_data_n[0]]
set_property  -dict {PACKAGE_PIN  AB6   IOSTANDARD LVDS} [get_ports phy_tx_data_p[1]]
set_property  -dict {PACKAGE_PIN  AC6   IOSTANDARD LVDS} [get_ports phy_tx_data_n[1]]
set_property  -dict {PACKAGE_PIN  AB8   IOSTANDARD LVDS} [get_ports phy_tx_data_p[2]]
set_property  -dict {PACKAGE_PIN  AC8   IOSTANDARD LVDS} [get_ports phy_tx_data_n[2]]
set_property  -dict {PACKAGE_PIN  AG9   IOSTANDARD LVDS} [get_ports phy_tx_data_p[3]]
set_property  -dict {PACKAGE_PIN  AH9   IOSTANDARD LVDS} [get_ports phy_tx_data_n[3]]
set_property  -dict {PACKAGE_PIN  AE9   IOSTANDARD LVDS} [get_ports phy_tx_data_p[4]]
set_property  -dict {PACKAGE_PIN  AE8   IOSTANDARD LVDS} [get_ports phy_tx_data_n[4]]
set_property  -dict {PACKAGE_PIN  AD7   IOSTANDARD LVDS} [get_ports phy_tx_data_p[5]]
set_property  -dict {PACKAGE_PIN  AE7   IOSTANDARD LVDS} [get_ports phy_tx_data_n[5]]
set_property  -dict {PACKAGE_PIN  AE5   IOSTANDARD LVDS} [get_ports phy_tx_frame_p]
set_property  -dict {PACKAGE_PIN  AF5   IOSTANDARD LVDS} [get_ports phy_tx_frame_n]
set_property  -dict {PACKAGE_PIN  AB1   IOSTANDARD LVCMOS18} [get_ports phy_txnrx]
set_property  -dict {PACKAGE_PIN  L5    IOSTANDARD LVCMOS18} [get_ports phy_enable]
set_property  -dict {PACKAGE_PIN  M6    IOSTANDARD LVCMOS18} [get_ports phy_en_agc]

set_property  -dict {PACKAGE_PIN  AF2   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_out[0]]
set_property  -dict {PACKAGE_PIN  AF1   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_out[1]]
set_property  -dict {PACKAGE_PIN  AD2   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_out[2]]
set_property  -dict {PACKAGE_PIN  AC4   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_out[3]]
set_property  -dict {PACKAGE_PIN  AB4   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_out[4]]
set_property  -dict {PACKAGE_PIN  N9    IOSTANDARD LVCMOS18} [get_ports phy_ctrl_out[5]]
set_property  -dict {PACKAGE_PIN  AD1   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_out[6]]
set_property  -dict {PACKAGE_PIN  AC1   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_out[7]]
set_property  -dict {PACKAGE_PIN  AB2   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_in[0]]
set_property  -dict {PACKAGE_PIN  AB3   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_in[1]]
set_property  -dict {PACKAGE_PIN  AD4   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_in[2]]
set_property  -dict {PACKAGE_PIN  AG4   IOSTANDARD LVCMOS18} [get_ports phy_ctrl_in[3]]

set_property  -dict {PACKAGE_PIN  L7    IOSTANDARD LVCMOS18} [get_ports phy_clk_out]
set_property  -dict {PACKAGE_PIN  P6    IOSTANDARD LVCMOS18} [get_ports phy_sync_in]

set_property  -dict {PACKAGE_PIN  N8    IOSTANDARD LVCMOS18} [get_ports phy_spi_clk]
set_property  -dict {PACKAGE_PIN  M8    IOSTANDARD LVCMOS18} [get_ports phy_spi_di]
set_property  -dict {PACKAGE_PIN  N7    IOSTANDARD LVCMOS18} [get_ports phy_spi_do]
set_property  -dict {PACKAGE_PIN  N6    IOSTANDARD LVCMOS18} [get_ports phy_spi_enb]
set_property  -dict {PACKAGE_PIN  P7    IOSTANDARD LVCMOS18} [get_ports phy_resetb]

set_property  -dict {PACKAGE_PIN  G11   IOSTANDARD LVCMOS33} [get_ports pwr_en_phy]

set_property  -dict {PACKAGE_PIN  E10   IOSTANDARD LVCMOS33} [get_ports mon_i2c_scl]
set_property  -dict {PACKAGE_PIN  D10   IOSTANDARD LVCMOS33} [get_ports mon_i2c_sda]

set_property  -dict {PACKAGE_PIN  D11   IOSTANDARD LVCMOS33} [get_ports rom_i2c_scl]
set_property  -dict {PACKAGE_PIN  E12   IOSTANDARD LVCMOS33} [get_ports rom_i2c_sda]

set_property  -dict {PACKAGE_PIN  D4    IOSTANDARD LVCMOS18} [get_ports pl_clk]
set_property  -dict {PACKAGE_PIN  A10   IOSTANDARD LVCMOS33} [get_ports pl_key]

set_property  -dict {PACKAGE_PIN  D12   IOSTANDARD LVCMOS33} [get_ports phy_gpo[0]]
set_property  -dict {PACKAGE_PIN  C12   IOSTANDARD LVCMOS33} [get_ports phy_gpo[1]]
set_property  -dict {PACKAGE_PIN  A12   IOSTANDARD LVCMOS33} [get_ports phy_gpo[2]]
set_property  -dict {PACKAGE_PIN  A11   IOSTANDARD LVCMOS33} [get_ports phy_gpo[3]]

# clocks

create_clock -name phy_data_clk -period 4.00    [get_ports phy_data_clk_p]
create_clock -name mon_i2c_scl  -period 2500    [get_ports mon_i2c_scl]
create_clock -name rom_i2c_scl  -period 2500    [get_ports rom_i2c_scl]
create_clock -name spi0_clk     -period 40      [get_pins -hier */EMIOSPI0SCLKO]
